// @(#)root/test:$Name:  $:$Id: MainEvent.cxx,v 1.31 2005/12/02 18:50:07 pcanal Exp $
// Author: Rene Brun   19/01/97

////////////////////////////////////////////////////////////////////////
//
//             A simple example with a ROOT tree
//             =================================
//
//  This program creates :
//    - a ROOT file
//    - a tree
// One possible argument : number of events
//   ---Running/Linking instructions----
//  This program consists of the following files and procedures.
//    - Event.h event class description
//    - Event.C event class implementation
//    - MainEvent.C the main program to demo this class might be used (this file)
//    - EventCint.C  the CINT dictionary for the event and Track classes
//        this file is automatically generated by rootcint (see Makefile),
//        when the class definition in Event.h is modified.
//
//   ---Analyzing the event.root file with the interactive root
//        example of a simple session
//   Root > TFile f("Event.root")
//   Root > T.Draw("feTrue")   //histogram true x
//   Root > T.Draw("feTrue:fIEvent","fIEvent<10") //histogram E true x vs event number for first 10 events
//
////////////////////////////////////////////////////////////////////////

#include <stdlib.h>

#include "Riostream.h"
#include "TROOT.h"
#include "TFile.h"
#include "TNetFile.h"
#include "TRandom.h"
#include "TTree.h"
#include "TBranch.h"
#include "TClonesArray.h"
#include "TStopwatch.h"
#include "CellAddress.h"
#include "CalCell.h"
#include "Event.h"
#include "CalorimeterGeometry.h"
#include "CalorimeterConstants.h"
#include "simulate.cxx"
#include "ana_simu.cxx"
#include "reconstruct.cxx"
#include "CalorimeterSimulation.h"
#include "TH1F.h"
#include "Utility.h"
#include "assert.h"
#include "TNtuple.h"
#include "TGraphErrors.h"
#include "TCanvas.h"
#include "TH2D.h"


//______________________________________________________________________________
int main(int argc, char **argv)
{
   Int_t nevent = 100;     // by default create 400 events
   if (argc > 1)  nevent = atoi(argv[1]);
   Int_t branchStyle = 1; //new style by default
   Int_t split=1;

   TFile *hfile;

   TTree *tree;
   Event *event = 0;

   // Fill event, header and tracks with some random numbers
   //   Create a timer object to benchmark this loop
   TStopwatch timer;
   timer.Start();
   Long64_t nb = 0;
   Int_t ev;
   Int_t bufsize;
   Int_t printev = 100;


   //Authorize Trees up to 2 Terabytes (if the system can do it)
   TTree::SetMaxTreeSize(1000*Long64_t(2000000000));


   // Create a new ROOT binary machine independent file.
   // Note that this file may contain any kind of ROOT objects, histograms,
   // pictures, graphics objects, detector geometries, tracks, events, etc..
   // This file is now becoming the current directory.
   hfile = new TFile("Event_10.root","RECREATE","TTree stage info root file");

   // Create a ROOT Tree and one superbranch
   tree = new TTree("T","Calo sim root tree");
   tree->SetAutoSave(1000000000);  // autosave when 1 Gbyte written
   bufsize = 64000;
   if (split) bufsize /= 4;
   event = new Event();
   TTree::SetBranchStyle(branchStyle);
   TBranch *branch = tree->Branch("event", &event, bufsize,split);
   branch->SetAutoDelete(kFALSE);
   if(split >= 0 && branchStyle) tree->BranchRef();


   gRandom->SetSeed();

   //histograms for resolution
   float E_min = -30.;
   float E_max = 30.;
   float XY_min = -.3;
   float XY_max = .3;

   //TH1F * E_h = new TH1F("E_h", "E_h", 30, E_min,E_max);

   TH1F * E_err = new TH1F("E_err", "E_err", 30, E_min,E_max);
   TH1F * X_err = new TH1F("X_err", "X_err", 100, XY_min, XY_max);
   TH1F * Y_err = new TH1F("Y_err", "Y_err", 100, XY_min, XY_max);

   TH1F * X_err_corr= new TH1F("X_err_corr", "X_err_corr", 100, XY_min, XY_max);
   TH1F * Y_err_corr = new TH1F("Y_err_corr", "Y_err_corr", 100, XY_min, XY_max);


   for (ev = 0; ev < nevent; ev++) {
         if (ev%printev == 0) {
            printf("event:%d \n",ev);
         }

         // initialize event
         event->build(ev);

        // simulation
	 simulate(event);

   reconstruct_event(event);
   E_err->Fill(event->get_eReco() - event->get_eTrue());
   X_err->Fill(event->get_fxReco() - event->get_x_impact());
   Y_err->Fill(event->get_fyReco() - event->get_y_impact());

   X_err_corr->Fill(event->get_fxReco_corr() - event->get_x_impact());
   Y_err_corr->Fill(event->get_fyReco_corr() - event->get_y_impact());

         nb += tree->Fill();  //fill the tree
        //event->seteReco(0);
      } // ev loop
      ana_simu(event,"hist_hadronic");
      std::vector<float> E_parameters = fit_par_gauss(E_err);
      std::cout<<"E_resolution = "<<E_parameters[2]<<std::endl;

      std::vector<float> X_parameters = fit_par_gauss(X_err);
      std::cout<<"X_resolution = "<<X_parameters[2]<<std::endl;

      std::vector<float> Y_parameters = fit_par_gauss(Y_err);
      std::cout<<"Y_resolution = "<<Y_parameters[2]<<std::endl;

      std::vector<float> X_parameters_corr = fit_par_gauss(X_err_corr);
      std::cout<<"X_resolution = "<<X_parameters[2]<<std::endl;

      std::vector<float> Y_parameters_corr = fit_par_gauss(Y_err_corr);
      std::cout<<"Y_resolution = "<<Y_parameters[2]<<std::endl;

      E_err->SaveAs("E_err.root");
      X_err->SaveAs("X_err.root");
      Y_err->SaveAs("Y_err.root");

      X_err_corr->SaveAs("X_err_corr.root");
      Y_err_corr->SaveAs("Y_err_corr.root");
      //std::vector<float> fit_results;
      //fit_results = fit_par_gauss(E_err);

      hfile = tree->GetCurrentFile(); //just in case we switched to a new file
      hfile->Write();
      tree->Print();


      hfile->Close();

std::cout<<"Program is done"<<std::endl;
   return 0;
}
